### ISSUE TITLE
Proper product release

### ISSUE THREAD

**Issue by thamsimun** [CS2103-AY1819S2-W14-2/main#108]
Update the version number in MainApp.java.

Generate a JAR file using Gradle.

Tag the repo with the version number. e.g. v1.2.1

Create a new release using GitHub and upload the JAR file you created.

**Comment by ghost** [comment]
This issue has been resolved with a pre-release `AddressBook.Jar` added to the **Releases** tabs. 
Please modify the feature list as needed.
