### ISSUE TITLE
[BUG] Files extension not filtered properly

### ISSUE THREAD

**Issue by thamsimun** [CS2103-AY1819S2-W14-2/main#148]
## Expected Behaviour
When importing a file that is not an image with the extension '.png', an error message should be thrown to user.

## Actual Behaviour
When importing a file that is not an image with the extension '.png', our application does nothing. If that particular file is in a folder, it prevents the importing of the images in that folder when you try to import the whole folder.

## Steps to Reproduce the Problem

  1. Get a pdf file
  2. Append '.png' to the filename
  3. Try importing

**Comment by ghost** [comment]
This issue is resolved with #193.
