### ISSUE TITLE
[BUG] Error thrown when file size too big

### ISSUE THREAD

**Issue by kayheen** [CS2103-AY1819S2-W14-2/main#165]
## Expected Behaviour
Should inform user that file size is too big 

## Actual Behaviour
Informed user that file path is wrong.

## Steps to Reproduce the Problem

1. Change the error message printed for the user.

**Comment by ghost** [comment]
This has been resolved as of #193.

**Comment by ghost** [comment]
An addendum will be added to User Guide to explain the 10MB image size limit.
