### ISSUE TITLE
[BUG] Codacy and AppVeyor badges missing from homepage.

### ISSUE THREAD

**Issue by ghost** [CS2103-AY1819S2-W14-2/main#245]
## Expected Behaviour
Codacy and AppVeyor badge should be shown on hompage.

## Actual Behaviour
Both badges are missing.

## Steps to Reproduce the Problem
N.A.

## Specifications

  - Version: FomoFoto 1.3.
  - Platform: Windows 10.
  - Subsystem: Java 9.

**Comment by thamsimun** [comment]
Appveyor badge is up already. @kayheen is doing up the codacy badge.
