### ISSUE TITLE
Exit command should clear temp/asset images.

### ISSUE THREAD

**Issue by ghost** [CS2103-AY1819S2-W14-2/main#31]
## Expected Behaviour
Images from asset folders should be cleared on application exit.

## Actual Behaviour
Images remain in folder on subsequent runs.

## Steps to Reproduce the Problem

  1. Import any image.
  2. Close application.
  3. Reopen application, image should still be in folder.

## Specifications

  - Version: Java 9.
  - Platform: Windows 10.
  - Subsystem: Intelli-J.

**Comment by itszp** [comment]
Files will be cleared by user to allow it to retain the images previously imported. User can continue editing them until they are cleared/exported.
