### ISSUE TITLE
User Stories

### ISSUE THREAD

**Issue by itszp** [CS2103-AY1819S2-W14-2/main#32]
### User Stories

**High Priority**

- [x] As a new user, I want get help by seeing usage instructions so that I can refer to instructions when I forget how to use the application.

- [x] As a user, I want to adjust the brightness of my photo so that I can make it brighter or darker.

- [x] As a user, I want to adjust the contrast of my photo.

- [x] As a user, I want to resize my photo.

- [x] As a user, I want to crop my photo so that I can trim it into my desired dimensions.

- [x] As a user, I want to rotate my photo so that I can change its orientation.

- [x] As a user, I want to undo and redo my edits so that I can revert or recover my changes.

- [x] As a user, I want to be able to save my image so that I can continue editing it the future.

- [x] As a user, I want to import my photo so that I can store a copy of the photo in the application for editing.

- [x] As a user, I want to export my photo so that I can save my edited photos to my computer. 

- [x] As a user, I want to open a photo that is stored in the application for editing.

- [x] As a photographer, I want to be able to watermark my photo so that I can prevent people from using my photo without my permission.

**Medium Priority**
- [x] As a user, I want to list the names of the photos stored in the application so that I can know what photos are currently stored inside. 

- [x] As a frequent user, I want to be able to create presets of edits so that I can easily apply a set of edits to my photos.

**Comment by kayheen** [comment]
This has been officially completed :)
