### ISSUE TITLE
Integrate Image Filters and Manipulations Functions to Open and Save.

### ISSUE THREAD

**Issue by itszp** [CS2103-AY1819S2-W14-2/main#71]
## Current Behaviour
Image filters and manipulations functions creates a copy of the original image with the same file name in temp folder. 

## Expected Behavior
Image filters and manipulations functions should only focus on editing the image inside temp folder. Once edited, functions will return the image to the temp folder, overwriting the previous temp image.

**Comment by kayheen** [comment]
this completed by @thamsimun in pull request #100

**Comment by kayheen** [comment]
this completed by @kayheen in pull request #101 and #102

**Comment by itszp** [comment]
Thanks @kayheen ! 
Done and closed
