### ISSUE TITLE
[BUG] Move Assets and Temp Folder to Storage Folder.

### ISSUE THREAD

**Issue by ghost** [CS2103-AY1819S2-W14-2/main#83]
## Expected Behaviour
`Assets` and `Temp` folder should be located in `storage` folder.

## Actual Behaviour
`Assets` and `Temp` folder should be located in `resources` folder.

## Steps to Reproduce the Problem

  1. Nil

## Specifications

  - Version: FomoFoto 1.2
  - Platform: Windows 10 
  - Subsystem: Java 9

**Comment by itszp** [comment]
I can help you do lol
