### ISSUE TITLE
[BUG] Some commands should use CurrentEdit now instead of Model

### ISSUE THREAD

**Issue by thamsimun** [CS2103-AY1819S2-W14-2/main#97]

**Comment by kayheen** [comment]
Brightness, Contrast, Black and White completed by @thamsimun in pull request #100

**Comment by kayheen** [comment]
Crop, Rotate completed by @kayheen in pull request #101

**Comment by kayheen** [comment]
Resize completed by @kayheen in pull request #102

**Comment by itszp** [comment]
`listfiles`, `open` and `save` has been shifted.

**Comment by thamsimun** [comment]
@Carrein please do not use methods in Model anymore

**Comment by thamsimun** [comment]
Resolved.
